server:
  port: 8082
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  exposed-headers: "*"
  allowed-headers: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: divineaura
    password: password
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 300
      idle-timeout: 60
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet